/**
 * Define all required Listings properties for HubSpot
 */
const LISTINGS_PROPERTIES = [
  {
    name: 'assetId',
    label: 'Asset ID',
    type: 'string',
    fieldType: 'text',
    groupName: 'listingsinformation',
    description: 'Unique identifier for the listing asset',
  },
  {
    name: 'listPrice',
    label: 'List Price',
    type: 'number',
    fieldType: 'number',
    groupName: 'listingsinformation',
    description: 'Listing price in dollars',
  },
  {
    name: 'listingStatus',
    label: 'Listing Status',
    type: 'string',
    fieldType: 'text',
    groupName: 'listingsinformation',
    description: 'Current status of the listing',
  },
  {
    name: 'propertyType',
    label: 'Property Type',
    type: 'string',
    fieldType: 'text',
    groupName: 'listingsinformation',
    description: 'Type of property (residential, commercial, etc.)',
  },
  {
    name: 'squareFootage',
    label: 'Square Footage',
    type: 'number',
    fieldType: 'number',
    groupName: 'listingsinformation',
    description: 'Square footage of the property',
  },
  {
    name: 'bathrooms',
    label: 'Bathrooms',
    type: 'number',
    fieldType: 'number',
    groupName: 'listingsinformation',
    description: 'Number of bathrooms',
  },
  {
    name: 'bedrooms',
    label: 'Bedrooms',
    type: 'number',
    fieldType: 'number',
    groupName: 'listingsinformation',
    description: 'Number of bedrooms',
  },
  {
    name: 'lotSize',
    label: 'Lot Size',
    type: 'number',
    fieldType: 'number',
    groupName: 'listingsinformation',
    description: 'Size of the lot',
  },
  {
    name: 'lotSizeUnits',
    label: 'Lot Size Units',
    type: 'string',
    fieldType: 'text',
    groupName: 'listingsinformation',
    description: 'Units for lot size (acres, sqft, etc.)',
  },
  {
    name: 'city',
    label: 'City',
    type: 'string',
    fieldType: 'text',
    groupName: 'listingsinformation',
    description: 'City where property is located',
  },
  {
    name: 'state',
    label: 'State',
    type: 'string',
    fieldType: 'text',
    groupName: 'listingsinformation',
    description: 'State where property is located',
  },
  {
    name: 'zip',
    label: 'ZIP Code',
    type: 'string',
    fieldType: 'text',
    groupName: 'listingsinformation',
    description: 'ZIP/Postal code',
  },
  {
    name: 'county',
    label: 'County',
    type: 'string',
    fieldType: 'text',
    groupName: 'listingsinformation',
    description: 'County where property is located',
  },
  {
    name: 'address1',
    label: 'Address Line 1',
    type: 'string',
    fieldType: 'text',
    groupName: 'listingsinformation',
    description: 'Primary address line',
  },
  {
    name: 'address2',
    label: 'Address Line 2',
    type: 'string',
    fieldType: 'text',
    groupName: 'listingsinformation',
    description: 'Secondary address line (apt, suite, etc.)',
  },
  {
    name: 'mediaUrl',
    label: 'Media URL',
    type: 'string',
    fieldType: 'text',
    groupName: 'listingsinformation',
    description: 'URL to property media/images',
  },
  {
    name: 'auctionStatus',
    label: 'Auction Status',
    type: 'string',
    fieldType: 'text',
    groupName: 'listingsinformation',
    description: 'Status of auction if applicable',
  },
  {
    name: 'auctionStartDate',
    label: 'Auction Start Date',
    type: 'datetime',
    fieldType: 'date',
    groupName: 'listingsinformation',
    description: 'Date when auction starts',
  },
  {
    name: 'auctionEndDate',
    label: 'Auction End Date',
    type: 'datetime',
    fieldType: 'date',
    groupName: 'listingsinformation',
    description: 'Date when auction ends',
  },
];

module.exports = {
  LISTINGS_PROPERTIES,
};
