/**
 * Define all required Listings properties for HubSpot
 */
const LISTINGS_PROPERTIES = [
  {
    name: 'assetId',
    label: 'Asset ID',
    type: 'string',
    fieldType: 'text',
    groupName: 'listing_information',
    description: 'Unique identifier for the listing asset',
  },
  {
    name: 'assetReferenceId',
    label: 'Asset Reference ID',
    type: 'string',
    fieldType: 'text',
    groupName: 'listing_information',
    description: 'Secondary reference identifier for the asset',
  },
  {
    name: 'listingStartDate',
    label: 'Listing Start Date',
    type: 'date',
    fieldType: 'date',
    groupName: 'listing_information',
    description: 'Date when the listing became active',
  },
  {
    name: 'listPrice',
    label: 'List Price',
    type: 'number',
    fieldType: 'number',
    groupName: 'listing_information',
    description: 'Listing price in dollars',
  },
  {
    name: 'listingStatus',
    label: 'Listing Status',
    type: 'enumeration',
    fieldType: 'select',
    groupName: 'listing_information',
    description: 'Current status of the listing',
    options: [
      { label: 'Active', value: 'active' },
      { label: 'Pending', value: 'pending' },
      { label: 'Sold', value: 'sold' },
      { label: 'Withdrawn', value: 'withdrawn' },
      { label: 'Expired', value: 'expired' },
      { label: 'Contingent', value: 'contingent' },
    ],
  },
  {
    name: 'propertyType',
    label: 'Property Type',
    type: 'enumeration',
    fieldType: 'select',
    groupName: 'listing_information',
    description: 'Type of property',
    options: [
      { label: 'Single Family', value: 'single_family' },
      { label: 'Condo', value: 'condo' },
      { label: 'Townhouse', value: 'townhouse' },
      { label: 'Multi-Family', value: 'multi_family' },
      { label: 'Land', value: 'land' },
      { label: 'Commercial', value: 'commercial' },
      { label: 'Other', value: 'other' },
    ],
  },
  {
    name: 'squareFootage',
    label: 'Square Footage',
    type: 'number',
    fieldType: 'number',
    groupName: 'listing_information',
    description: 'Square footage of the property',
  },
  {
    name: 'bathrooms',
    label: 'Bathrooms',
    type: 'number',
    fieldType: 'number',
    groupName: 'listing_information',
    description: 'Number of bathrooms',
  },
  {
    name: 'bedrooms',
    label: 'Bedrooms',
    type: 'number',
    fieldType: 'number',
    groupName: 'listing_information',
    description: 'Number of bedrooms',
  },
  {
    name: 'lotSize',
    label: 'Lot Size',
    type: 'number',
    fieldType: 'number',
    groupName: 'listing_information',
    description: 'Size of the lot',
  },
  {
    name: 'lotSizeUnits',
    label: 'Lot Size Units',
    type: 'enumeration',
    fieldType: 'select',
    groupName: 'listing_information',
    description: 'Units for lot size',
    options: [
      { label: 'Square Feet', value: 'sqft' },
      { label: 'Acres', value: 'acres' },
      { label: 'Square Meters', value: 'sqm' },
    ],
  },
  {
    name: 'city',
    label: 'City',
    type: 'string',
    fieldType: 'text',
    groupName: 'listing_information',
    description: 'City where property is located',
  },
  {
    name: 'state',
    label: 'State',
    type: 'string',
    fieldType: 'text',
    groupName: 'listing_information',
    description: 'State where property is located',
  },
  {
    name: 'zip',
    label: 'ZIP Code',
    type: 'string',
    fieldType: 'text',
    groupName: 'listing_information',
    description: 'ZIP/Postal code',
  },
  {
    name: 'county',
    label: 'County',
    type: 'string',
    fieldType: 'text',
    groupName: 'listing_information',
    description: 'County where property is located',
  },
  {
    name: 'addressLine1',
    label: 'Address Line 1',
    type: 'string',
    fieldType: 'text',
    groupName: 'listing_information',
    description: 'Primary address line',
  },
  {
    name: 'addressLine2',
    label: 'Address Line 2',
    type: 'string',
    fieldType: 'text',
    groupName: 'listing_information',
    description: 'Secondary address line (apt, suite, etc.)',
  },
  {
    name: 'mediaUrl',
    label: 'Media URL',
    type: 'string',
    fieldType: 'text',
    groupName: 'listing_information',
    description: 'URL to property media/images',
  },
  {
    name: 'auctionStatus',
    label: 'Auction Status',
    type: 'enumeration',
    fieldType: 'select',
    groupName: 'listing_information',
    description: 'Status of auction if applicable',
    options: [
      { label: 'Not on Auction', value: 'not_on_auction' },
      { label: 'Upcoming', value: 'upcoming' },
      { label: 'Active', value: 'active' },
      { label: 'Ended', value: 'ended' },
      { label: 'Sold', value: 'sold' },
    ],
  },
  {
    name: 'auctionStartDate',
    label: 'Auction Start Date',
    type: 'date',
    fieldType: 'date',
    groupName: 'listing_information',
    description: 'Date when auction starts',
  },
  {
    name: 'auctionEndDate',
    label: 'Auction End Date',
    type: 'date',
    fieldType: 'date',
    groupName: 'listing_information',
    description: 'Date when auction ends',
  },
];

module.exports = {
  LISTINGS_PROPERTIES,
};
